# Generated by Django 4.0.5 on 2022-07-05 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
