# Generated by Django 4.0.5 on 2022-07-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_category_id_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_pirce',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
