# Generated by Django 4.0.5 on 2022-07-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_total_pirce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='goal_pirce',
            new_name='goal_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='total_pirce',
            new_name='total_price',
        ),
    ]
