# Generated by Django 4.0.5 on 2022-07-06 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
