# Generated by Django 4.0.5 on 2022-07-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_username_user_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.CharField(default='https://cdn.pixabay.com/photo/2017/09/10/18/25/question-2736480_1280.jpg', max_length=200),
        ),
    ]
